### ISSUE TITLE
Remove poignant guide from required readings.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-study#104]
It's too long for a requirement.

**Comment by gaand** [comment]
But keep it in an additional resources section.

**Comment by jrhorn424** [comment]
Would reverting https://github.com/ga-wdi-boston/ruby-study/commit/41fd6884b6abee7880d5794f88a126737afb0232 be ok, or would you like to see the Ruby Bits free levels moved into required?

**Comment by gaand** [comment]
I think @bernardlee was attempting to more closely hue to the template.  I think we need to have the additional resources section available in https://github.com/ga-wdi-boston/study-template/blob/master/study.md and perhaps other template markdown files.

**Comment by bernardlee** [comment]
I'll fix this since I made the mistake.

**Comment by raq929** [comment]
Fixed with a80f1c906b852ae2916103d66f317e7a2460f99a
