### ISSUE TITLE
Find more practice problems for ruby-study.

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ruby-study#19]

**Comment by RealWeeks** [comment]
@payne-chris-r It's kind of long already isn't it? There are two required readings/practices and 2 optional ones. If devs want more practice they should do the optional readings/practices/

**Comment by gaand** [comment]
I'm with @J-Weeks on this.  What kind of practice are you suggesting @payne-chris-r ?

Add ruby koans?  That seems like too much.

**Comment by BenGitsCode** [comment]
I'm going to hold off on this issue without consensus, but it sounds like we're leaning more towards recommending resources than including more practice prolbems here?

**Comment by gaand** [comment]
It's hard to say without a response from @payne-chris-r

**Comment by BenGitsCode** [comment]
That's why I figured I'd leave it open for now. 

I was going to add rubymonk as an additional resource but it appears to be down/gone.

**Comment by bernardlee** [comment]
How about doing the tutorial on Codecademy or some Project Euler problems using Ruby?

**Comment by BenGitsCode** [comment]
I think the intro ruby tutorials on codeschool would be great for a study. Maybe something like [this](http://rubyquiz.com/) for developers that are looking for more of a challenge?

**Comment by raq929** [comment]
I think this has likely been addressed.

**Comment by gaand** [comment]
@raq929 not without a reply from @payne-chris-r

**Comment by payne-chris-r** [comment]
Sorry, apparently I was hibernating. Reviewing now.

**Comment by payne-chris-r** [comment]
@raq929 do you know which commit addresses this? The only thing I could find was this:
```diff
-  [Poignant Guide](http://poignant.guide/)		 
```
I don't think it's been addressed. I also don't remember why I opened this in the first place. My guess is devs in `012` wanted "more ruby practice" or something like that. Or @jrhorn424 asked me to open it? To Jason's point, I don't know how long it is. Maybe it is long enough. Maybe Not. I don't think I can be of much help without a full audit of this study, but as far as I can tell NO new practice problems were added to this study...

**Comment by gaand** [comment]
I take it back.  Add ruby koans.  Make sure the additional resources section is denoted as optional.

Maybe point to codewars?  Do we require them to sign up?  They can just use github.com oauth.

**Comment by Jcornmanhomonoff** [comment]
I added a reference to ruby koans & denoted the additional resources as optional but did not point to codewars. Unsure what the ultimate end goal of this issue should be.

**Comment by gaand** [comment]
@payne-chris-r I'm closing this as it seems the original issue has been addressed.  Feel free to reopen if you disagree.
