### ISSUE TITLE
Suggested study

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-study#2]
These:
- http://tryruby.org/
- https://www.ruby-lang.org/en/documentation/quickstart/

possibly others.  I haven't found a good reference that covers `%` string quoting

**Comment by gaand** [comment]
Have them begin http://poignant.guide/.  Make sure they don't try and read it all.  Have them read a little bit every day/week.

**Comment by RealWeeks** [comment]
@gaand Okay to close?

**Comment by gaand** [comment]
Final bit split out into #17
